version: '3.8'

services:
  postgres:
    image: crpi-wh1i56a4x558rrhm.cn-hangzhou.personal.cr.aliyuncs.com/changqinga/postgres:16-alpine
    container_name: reader_postgres
    environment:
      POSTGRES_DB: reader_qaq
      POSTGRES_USER: reader
      POSTGRES_PASSWORD: reader_dev_password
      TZ: UTC
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reader"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - reader_network

  redis:
    image: crpi-wh1i56a4x558rrhm.cn-hangzhou.personal.cr.aliyuncs.com/changqinga/valkey:8
    container_name: reader_redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --requirepass reader_dev_password
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - reader_network

  minio:
    image: crpi-wh1i56a4x558rrhm.cn-hangzhou.personal.cr.aliyuncs.com/changqinga/minio:RELEASE.2023-12-20T01-00-02Z
    container_name: reader_minio
    environment:
      MINIO_ROOT_USER: reader
      MINIO_ROOT_PASSWORD: reader_dev_password
    ports:
      - "8999:9000"
      - "9002:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - reader_network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  reader_network:
    driver: bridge

